apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flight2bq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flight2bq
    spec:
      volumes:
        - name: keyfile
          secret:
            secretName: flight2bqkey
      containers:
      - name: flight2bq
        image: gcr.io/alex-olivier/flight2bq:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: keyfile
            mountPath: /config
            readOnly: true
        env:
          - name: PROJECT
            value: "alex-olivier"
          - name: DATASET
            value: "flighttracker_prod"
          - name: TABLE
            value: "aircraft_stream"
          - name: SUBSCRIPTION
            value: "flight-data-prod"
          - name: KEYFILE
            value: /config/flight2bqkey